"""Shared utilities for the NeuralForge companion repository."""

from .autograd import Value, graph_summary
from .calculus import GradientCheckResult, check_gradient, numerical_derivative, numerical_gradient
from .data_preparation import SplitIndices, Standardizer, random_split_indices, select_rows, stratified_split_indices
from .eda import Histogram, NumericSummary, describe, histogram, iqr_outlier_mask, quantile, scatter_svg, write_scatter_svg
from .foundations import LogisticNeuron, TrainingResult, binary_cross_entropy, sigmoid, train_logistic_neuron
from .gradient_flow import (
    GradientHealth,
    GradientStats,
    assess_gradient_health,
    gradient_stats,
    gradient_to_parameter_ratio,
    group_gradient_stats,
    require_finite_gradients,
)
from .initialization import (
    SignalStats,
    activate,
    dense_forward,
    initialize_matrix,
    initialization_scale,
    propagate_signal,
    recommend_initialization,
)
from .linear_algebra import cosine_similarity, dot, l2_norm, matmul, outer, transpose
from .logistic_regression import LogisticRegression, LogisticRegressionResult, train_logistic_regression
from .losses import (
    OutputDesign,
    absolute,
    binary_cross_entropy_with_logits,
    categorical_cross_entropy_with_logits,
    huber_loss,
    logsumexp,
    mean_absolute_error,
    mean_categorical_cross_entropy_with_logits,
    mean_squared_error as loss_mean_squared_error,
    recommend_output_design,
    softplus,
)
from .neuron import ArtificialNeuron, NeuronTrace, activation_derivative, identity, leaky_relu, relu
from .nn import Layer, MLP, Module, Neuron, binary_cross_entropy_loss, mean_squared_error, sgd_step
from .normalization import (
    BatchNormalizationResult,
    LayerNormalizationResult,
    RunningMoments,
    batch_normalize,
    layer_normalize,
    normalization_parameters,
    stable_softmax,
)
from .optim import Adam, Momentum, Optimizer, RMSProp, SGD, clip_grad_norm
from .perceptron import Perceptron, PerceptronResult, train_perceptron
from .regularization import (
    DropoutResult,
    EarlyStopping,
    generalization_gap,
    inverted_dropout,
    l1_penalty,
    l2_penalty,
    parameter_l2_norm,
    regularized_loss,
)
from .reproducibility import SeedReport, set_global_seed
from .schedules import (
    PlateauUpdate,
    ReduceLROnPlateau,
    constant_lr,
    cosine_decay,
    exponential_decay,
    linear_warmup,
    step_decay,
    warmup_cosine_decay,
)
from .statistics import BootstrapEstimate, bernoulli_log_likelihood, bootstrap_mean_interval, correlation, covariance, mean, normal_pdf, standard_deviation, variance
from .tensor_basics import flatten, infer_shape, numel, reshape
from .training import (
    EpochRecord,
    ExperimentConfig,
    ExperimentResult,
    build_optimizer,
    run_regression_experiment,
    run_training_loop,
    write_experiment_json,
)

__all__ = [
    "Adam",
    "ArtificialNeuron",
    "BatchNormalizationResult",
    "BootstrapEstimate",
    "DropoutResult",
    "EarlyStopping",
    "EpochRecord",
    "ExperimentConfig",
    "ExperimentResult",
    "GradientCheckResult",
    "GradientHealth",
    "GradientStats",
    "Histogram",
    "Layer",
    "LayerNormalizationResult",
    "LogisticNeuron",
    "LogisticRegression",
    "LogisticRegressionResult",
    "MLP",
    "Module",
    "Momentum",
    "Neuron",
    "NeuronTrace",
    "NumericSummary",
    "Optimizer",
    "OutputDesign",
    "Perceptron",
    "PerceptronResult",
    "PlateauUpdate",
    "RMSProp",
    "ReduceLROnPlateau",
    "RunningMoments",
    "SGD",
    "SeedReport",
    "SignalStats",
    "SplitIndices",
    "Standardizer",
    "TrainingResult",
    "Value",
    "absolute",
    "activate",
    "activation_derivative",
    "assess_gradient_health",
    "batch_normalize",
    "bernoulli_log_likelihood",
    "binary_cross_entropy",
    "binary_cross_entropy_loss",
    "binary_cross_entropy_with_logits",
    "bootstrap_mean_interval",
    "build_optimizer",
    "categorical_cross_entropy_with_logits",
    "check_gradient",
    "clip_grad_norm",
    "constant_lr",
    "correlation",
    "cosine_decay",
    "cosine_similarity",
    "covariance",
    "dense_forward",
    "describe",
    "dot",
    "exponential_decay",
    "flatten",
    "generalization_gap",
    "gradient_stats",
    "gradient_to_parameter_ratio",
    "graph_summary",
    "group_gradient_stats",
    "histogram",
    "huber_loss",
    "identity",
    "infer_shape",
    "initialization_scale",
    "initialize_matrix",
    "inverted_dropout",
    "iqr_outlier_mask",
    "l1_penalty",
    "l2_norm",
    "l2_penalty",
    "layer_normalize",
    "leaky_relu",
    "linear_warmup",
    "logsumexp",
    "loss_mean_squared_error",
    "matmul",
    "mean",
    "mean_absolute_error",
    "mean_categorical_cross_entropy_with_logits",
    "mean_squared_error",
    "normal_pdf",
    "normalization_parameters",
    "numel",
    "numerical_derivative",
    "numerical_gradient",
    "outer",
    "parameter_l2_norm",
    "propagate_signal",
    "quantile",
    "random_split_indices",
    "recommend_initialization",
    "recommend_output_design",
    "regularized_loss",
    "relu",
    "require_finite_gradients",
    "reshape",
    "run_regression_experiment",
    "run_training_loop",
    "scatter_svg",
    "select_rows",
    "set_global_seed",
    "sgd_step",
    "sigmoid",
    "softplus",
    "stable_softmax",
    "standard_deviation",
    "step_decay",
    "stratified_split_indices",
    "train_logistic_neuron",
    "train_logistic_regression",
    "train_perceptron",
    "transpose",
    "variance",
    "warmup_cosine_decay",
    "write_experiment_json",
    "write_scatter_svg",
]
__version__ = "0.1.0"
