"""Shared utilities for the NeuralForge companion repository."""

from .autograd import Value, graph_summary
from .calculus import GradientCheckResult, check_gradient, numerical_derivative, numerical_gradient
from .data_preparation import SplitIndices, Standardizer, random_split_indices, select_rows, stratified_split_indices
from .eda import Histogram, NumericSummary, describe, histogram, iqr_outlier_mask, quantile, scatter_svg, write_scatter_svg
from .foundations import LogisticNeuron, TrainingResult, binary_cross_entropy, sigmoid, train_logistic_neuron
from .gradient_flow import (
    GradientFlowReport,
    GradientStats,
    LayerGradientReport,
    classify_gradient_health,
    gradient_flow_report,
    gradient_statistics,
    mlp_parameter_groups,
    relative_update_ratio,
)
from .initialization import (
    InitializationPlan,
    SignalPropagationProfile,
    initialization_plan,
    initialize_matrix,
    population_variance,
    signal_propagation_profile,
)
from .linear_algebra import cosine_similarity, dot, l2_norm, matmul, outer, transpose
from .logistic_regression import LogisticRegression, LogisticRegressionResult, train_logistic_regression
from .losses import (
    OutputLossPairing,
    binary_cross_entropy_with_logits,
    huber_loss,
    mean_absolute_error,
    multiclass_cross_entropy,
    recommended_output_loss,
    softplus,
)
from .neuron import ArtificialNeuron, NeuronTrace, activation_derivative, identity, leaky_relu, relu
from .nn import Layer, MLP, Module, Neuron, binary_cross_entropy_loss, mean_squared_error, sgd_step
from .normalization import (
    BatchNormalizationResult,
    LayerNormalizationResult,
    RunningMoments,
    batch_normalize,
    layer_normalize,
    normalization_parameters,
    stable_softmax,
)
from .optim import Adam, Momentum, Optimizer, RMSProp, SGD, clip_grad_norm
from .perceptron import Perceptron, PerceptronResult, train_perceptron
from .regularization import (
    DropoutResult,
    EarlyStopping,
    generalization_gap,
    inverted_dropout,
    l1_penalty,
    l2_penalty,
    parameter_l2_norm,
    regularized_loss,
)
from .reproducibility import SeedReport, set_global_seed
from .schedules import (
    ReduceLROnPlateau,
    apply_learning_rate,
    constant_learning_rate,
    cosine_decay,
    exponential_decay,
    linear_warmup,
    step_decay,
    warmup_cosine_decay,
)
from .statistics import BootstrapEstimate, bernoulli_log_likelihood, bootstrap_mean_interval, correlation, covariance, mean, normal_pdf, standard_deviation, variance
from .tensor_basics import flatten, infer_shape, numel, reshape
from .training import (
    EpochRecord,
    ExperimentConfig,
    ExperimentResult,
    config_fingerprint,
    data_fingerprint,
    run_regression_experiment,
)

__all__ = [
    "Adam",
    "ArtificialNeuron",
    "BatchNormalizationResult",
    "BootstrapEstimate",
    "DropoutResult",
    "EarlyStopping",
    "EpochRecord",
    "ExperimentConfig",
    "ExperimentResult",
    "GradientCheckResult",
    "GradientFlowReport",
    "GradientStats",
    "Histogram",
    "InitializationPlan",
    "Layer",
    "LayerGradientReport",
    "LayerNormalizationResult",
    "LogisticNeuron",
    "LogisticRegression",
    "LogisticRegressionResult",
    "MLP",
    "Module",
    "Momentum",
    "Neuron",
    "NeuronTrace",
    "NumericSummary",
    "Optimizer",
    "OutputLossPairing",
    "Perceptron",
    "PerceptronResult",
    "RMSProp",
    "ReduceLROnPlateau",
    "RunningMoments",
    "SGD",
    "SeedReport",
    "SignalPropagationProfile",
    "SplitIndices",
    "Standardizer",
    "TrainingResult",
    "Value",
    "activation_derivative",
    "apply_learning_rate",
    "batch_normalize",
    "bernoulli_log_likelihood",
    "binary_cross_entropy",
    "binary_cross_entropy_loss",
    "binary_cross_entropy_with_logits",
    "bootstrap_mean_interval",
    "check_gradient",
    "classify_gradient_health",
    "clip_grad_norm",
    "config_fingerprint",
    "constant_learning_rate",
    "correlation",
    "cosine_decay",
    "cosine_similarity",
    "covariance",
    "data_fingerprint",
    "describe",
    "dot",
    "exponential_decay",
    "flatten",
    "generalization_gap",
    "gradient_flow_report",
    "gradient_statistics",
    "graph_summary",
    "histogram",
    "huber_loss",
    "identity",
    "infer_shape",
    "initialization_plan",
    "initialize_matrix",
    "inverted_dropout",
    "iqr_outlier_mask",
    "l1_penalty",
    "l2_norm",
    "l2_penalty",
    "layer_normalize",
    "leaky_relu",
    "linear_warmup",
    "matmul",
    "mean",
    "mean_absolute_error",
    "mean_squared_error",
    "mlp_parameter_groups",
    "multiclass_cross_entropy",
    "normal_pdf",
    "normalization_parameters",
    "numel",
    "numerical_derivative",
    "numerical_gradient",
    "outer",
    "parameter_l2_norm",
    "population_variance",
    "quantile",
    "random_split_indices",
    "recommended_output_loss",
    "regularized_loss",
    "relative_update_ratio",
    "relu",
    "reshape",
    "run_regression_experiment",
    "scatter_svg",
    "select_rows",
    "set_global_seed",
    "sgd_step",
    "sigmoid",
    "signal_propagation_profile",
    "softplus",
    "stable_softmax",
    "standard_deviation",
    "step_decay",
    "stratified_split_indices",
    "train_logistic_neuron",
    "train_logistic_regression",
    "train_perceptron",
    "transpose",
    "variance",
    "warmup_cosine_decay",
    "write_scatter_svg",
]
__version__ = "0.1.0"
