"""Public vision namespace for NeuralForge Parts 021-025."""

from .cnn_architecture import (
    ArchitectureReport,
    ConvLayerSpec,
    LayerReport,
    PoolLayerSpec,
    analyze_cnn_architecture,
    conv_mac_count,
    conv_parameter_count,
    lenet_style_specs,
    residual_compatible,
)
from .convolution import (
    average_pool2d,
    conv2d,
    effective_kernel_size,
    max_pool2d,
    output_size,
    pad2d,
    pool2d,
    same_padding,
)
from .detection import (
    BoundingBox,
    DetectionEvaluation,
    DetectionMatch,
    evaluate_detections,
    intersection_over_union,
    iou_matrix,
    non_maximum_suppression,
)
from .mobile_vision import (
    VisionCost,
    depthwise_separable_cost,
    inverted_residual_cost,
    model_size_bytes,
    model_size_mebibytes,
    standard_conv_cost,
    width_scaled_channels,
)
from .segmentation import (
    ClassSegmentationMetrics,
    PanopticMetrics,
    SegmentationReport,
    binary_dice_score,
    binary_mask_iou,
    confusion_matrix,
    panoptic_quality,
    segmentation_report,
)

__all__ = [
    "ArchitectureReport",
    "BoundingBox",
    "ClassSegmentationMetrics",
    "ConvLayerSpec",
    "DetectionEvaluation",
    "DetectionMatch",
    "LayerReport",
    "PanopticMetrics",
    "PoolLayerSpec",
    "SegmentationReport",
    "VisionCost",
    "analyze_cnn_architecture",
    "average_pool2d",
    "binary_dice_score",
    "binary_mask_iou",
    "confusion_matrix",
    "conv2d",
    "conv_mac_count",
    "conv_parameter_count",
    "depthwise_separable_cost",
    "effective_kernel_size",
    "evaluate_detections",
    "intersection_over_union",
    "inverted_residual_cost",
    "iou_matrix",
    "lenet_style_specs",
    "max_pool2d",
    "model_size_bytes",
    "model_size_mebibytes",
    "non_maximum_suppression",
    "output_size",
    "pad2d",
    "panoptic_quality",
    "pool2d",
    "residual_compatible",
    "same_padding",
    "segmentation_report",
    "standard_conv_cost",
    "width_scaled_channels",
]
